load("@gazelle//:def.bzl", "gazelle")
load("@rules_go//go:def.bzl", "go_binary", "go_library")
load("//tools/nogo:nogo.bzl", "setup_nogo")

# gazelle:proto disable_global
gazelle(name = "gazelle")

# This registers the nogo target defined in tools/nogo
setup_nogo()

go_library(
    name = "garf_lib",
    srcs = ["garf.go"],
    importpath = "github.com/albertocavalcante/garf",
    visibility = ["//visibility:private"],
    deps = [
        "//cmd",
    ],
)

go_binary(
    name = "garf",
    embed = [":garf_lib"],
    visibility = ["//visibility:public"],
)

[
    go_binary(
        name = "garf-%s-%s" % (os, arch),
        embed = [":garf_lib"],
        gc_linkopts = [
            "-s",
            "-w",
        ],
        goarch = arch,
        goos = os,
        pure = "off",
        visibility = ["//visibility:public"],
    )
    for os, arch in [
        ("linux", "amd64"),
        ("linux", "arm64"),
    ]
]

[
    go_binary(
        name = "garf-%s-%s" % (os, arch),
        embed = [":garf_lib"],
        goarch = arch,
        goos = os,
        pure = "off",
        visibility = ["//visibility:public"],
    )
    for os, arch in [
        ("windows", "amd64"),
        ("windows", "arm64"),
    ]
]
