load("@gazelle//:def.bzl", "gazelle")
load("@rules_go//go:def.bzl", "go_binary", "go_library")
load("//private:go_binary.bzl", "cross_platform_go_binary")
load("//tools/nogo:nogo.bzl", "setup_nogo")

alias(
    name = "go",
    actual = "@rules_go//go:go",
)

# gazelle:proto disable_global
gazelle(name = "gazelle")

# This registers the nogo target defined in tools/nogo
setup_nogo()

go_library(
    name = "garf_lib",
    srcs = ["garf.go"],
    importpath = "github.com/albertocavalcante/garf",
    visibility = ["//visibility:private"],
    deps = [
        "//cmd",
    ],
)

go_binary(
    name = "garf",
    embed = [":garf_lib"],
    visibility = ["//visibility:public"],
)

cross_platform_go_binary(
    name = "garf-bin",
    embed = [":garf_lib"],
)
