"""garf"""

module(
    name = "garf",
    version = "0.5.6",
)

bazel_dep(name = "platforms", version = "1.0.0")
bazel_dep(name = "rules_go", version = "0.63.0")
bazel_dep(name = "gazelle", version = "0.47.0")
bazel_dep(name = "aspect_bazel_lib", version = "2.21.2")
bazel_dep(name = "buildifier_prebuilt", version = "8.2.1.1")
bazel_dep(name = "bazel_env.bzl", version = "0.5.0")

go_sdk = use_extension("@rules_go//go:extensions.bzl", "go_sdk")
go_sdk.download(version = "1.24.4")
go_sdk.nogo(nogo = "//:garf_nogo")

go_deps = use_extension("@gazelle//:extensions.bzl", "go_deps")
go_deps.from_file(go_mod = "//:go.mod")

nogo_deps = use_extension("@gazelle//:extensions.bzl", "go_deps", isolate = True)
nogo_deps.from_file(go_mod = "//tools/nogo:go.mod")
use_repo(
    nogo_deps,
    "com_github_nishanths_exhaustive",
    "org_golang_x_tools",
)

use_repo(
    go_deps,
    "com_github_albertocavalcante_netrcgo",
    "com_github_cloudsmith_io_cloudsmith_api_go",
    "com_github_jfrog_jfrog_client_go",
    "com_github_sirupsen_logrus",
    "com_github_spf13_cobra",
    "com_github_spf13_viper",
    "com_github_stretchr_testify",
    "in_gopkg_yaml_v3",
)
