load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "core",
    srcs = [
        "jfrog_client.go",
        "static_client.go",
        "unzip.go",
    ],
    importpath = "github.com/albertocavalcante/garf/core",
    visibility = ["//visibility:public"],
    deps = [
        "//pkg/core",
        "//pkg/io/progress",
        "@com_github_jfrog_jfrog_client_go//artifactory",
        "@com_github_jfrog_jfrog_client_go//artifactory/auth",
        "@com_github_jfrog_jfrog_client_go//artifactory/services",
        "@com_github_jfrog_jfrog_client_go//artifactory/services/utils",
        "@com_github_jfrog_jfrog_client_go//config",
    ],
)

go_test(
    name = "core_test",
    size = "small",
    srcs = [
        "jfrog_client_test.go",
        "unzip_test.go",
    ],
    deps = [
        ":core",
        "@com_github_stretchr_testify//require",
    ],
)
