load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "cmd",
    srcs = [
        "mirror.go",
        "root.go",
        "version.go",
    ],
    importpath = "github.com/albertocavalcante/garf/cmd",
    visibility = ["//visibility:public"],
    deps = [
        "//artifact",
        "//core",
        "@com_github_spf13_cobra//:cobra",
    ],
)

go_test(
    name = "cmd_test",
    size = "small",
    srcs = [
        "mirror_test.go",
        "version_test.go",
    ],
    embed = [":cmd"],
    deps = [
        "//artifact",
        "@com_github_stretchr_testify//require",
    ],
)
