load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "netrc",
    srcs = ["netrc.go"],
    importpath = "github.com/albertocavalcante/garf/pkg/netrc",
    visibility = ["//visibility:public"],
)

go_test(
    name = "netrc_test",
    size = "small",
    srcs = ["netrc_test.go"],
    deps = [
        ":netrc",
        "//pkg/testutil",
        "@com_github_stretchr_testify//require",
    ],
)
